# Generated by Django 6.0.2 on 2026-02-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(max_length=20, unique=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('duration', models.CharField(choices=[('6', '6 Months'), ('12', '1 Year'), ('24', '2 Years')], default='6', max_length=2)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
